### ISSUE TITLE
Better automated cw testing

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#102]
Let's kill it a million times, till it becomes immortal.

(I will use this as a tracking issue for work on cw pre-moneta.)

**Comment by the-frey** [comment]
Part of the codebase for several projects:

- DAODAO
- Junoswap
- Whoami

Contains a quickstart script that could be used to attempt to store a contract with `-b block` and check storage has been successful. Suggest DAODAO as it's larger and has submessages in the instantiation step.

**Comment by the-frey** [comment]
closed by #136
