### ISSUE TITLE
Error querying pinned contracts from wasm module

### ISSUE THREAD

**Issue by elsehow** [CosmosContracts/juno#106]
Querying pinned contracts doesn't work:

```
$ junod query wasm pinned

Error: error unmarshalling: invalid character '<' looking for beginning of value
```

This may be an upstream issue in [wasmd](https://github.com/CosmWasm/wasmd).

**Comment by giansalex** [comment]
works for me
![image](https://user-images.githubusercontent.com/14926587/143933160-767bdf0b-0eab-45c8-8a7d-a8c41ab9d190.png)

is your node sync?
