### ISSUE TITLE
Contract submessages trigger msgRouter is nil panic

### ISSUE THREAD

**Issue by the-frey** [CosmosContracts/juno#127]
Full error:

```
Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: dispatch: submessages: >>> msgRouter is nil!!!: panic: invalid request
```

The bug is in the wasmd fork by the look of it.

- `v2.0.3` of juno does not have the issue.
- `v2.0.4` of juno and above does.

#126 does not have the issue, solved by rolling back those two dependencies. It turns out gas config costs have nothing to do with it.

**Comment by zlounes** [comment]
As discussed in Telegram, we have the same problem on JunoMint.

**Comment by the-frey** [comment]
Yes, so as @zlounes says, any contract (e.g. JunoMint, DAODAO) that uses SubMessages is currently unable to execute those handlers on mainnet.

**Comment by the-frey** [comment]
cc @JakeHartnell

**Comment by the-frey** [comment]
fixed in wasmd and ver bumped. Upgraded by handler #135
