### ISSUE TITLE
Contract Address Length

### ISSUE THREAD

**Issue by the-frey** [CosmosContracts/juno#132]
It is shorter since `v2.0.3` -> we need to increase in order to be forwards compatible with mainline.

Terse ticket for now. Let's discuss fix and upgrade path.

cc @dimiandre @JakeHartnell @faddat @giansalex

**Comment by the-frey** [comment]
See https://github.com/cosmwasm/wasmd/issues/685#issuecomment-981547822

**Comment by giansalex** [comment]
v1.0.0-juno | v1.0.0-juno3
![image](https://user-images.githubusercontent.com/14926587/146558183-63978014-a3e5-4129-b82b-98a5fe7ad31a.png)

https://github.com/notional-labs/wasmd/blob/v1.0.0-juno3/x/wasm/keeper/keeper.go#L880

**Comment by the-frey** [comment]
So in terms of an upgrade path - we need to write a migration that:

- Looks up all contracts currently instantiated
- Replaces their contract addr with a 32 byte version?

Luckily not many contracts deployed yet 🤔

**Comment by the-frey** [comment]
fixed in wasmd and upgraded in #135
