### ISSUE TITLE
Generated genesis file doesn't work.

### ISSUE THREAD

**Issue by JakeHartnell** [CosmosContracts/Juno#15]
Recent version here: https://github.com/CosmosContracts/testnets/blob/main/juno-testnet-7/genesis.json

When it's run it throws an error:
```
panic: invariant broken: bank: total supply invariant
        sum of accounts coins: 72819737204316ujuno
        supply.Total:          52819737204316ujuno
```

**Comment by blockcreators** [comment]
Denis from discord said:

> When a genesis file is exported the bank module exports supply. In the genesis file above it's an empty array, is there a reason for this? The cosmoshub-4 genesis, for example, has the following value:

```

"supply": [
  {
    "amount": "268335648775167",
    "denom": "uatom"
  }
]
```

**Comment by faddat** [comment]
Good sir block creator, can you please link to the Genesis file that you're referring to using an IPFS CID so that I know exactly what file you're talking about?

For example, are you referring to our current Genesis file or are you referring to the one from the hub?

**Comment by the-frey** [comment]
I assume the one on Github in the testnets repo?

**Comment by the-frey** [comment]
(the one Jake has linked)

**Comment by faddat** [comment]
Yeah, I think I was temporarily blind.  Thanks!

**Comment by the-frey** [comment]
How was this genesis file generated? When was it generated?

**Comment by the-frey** [comment]
The gap between those two numbers is exactly `20000000000000` which makes me think it's not a percentage - so it can't be the e.g. community pool right?

**Comment by the-frey** [comment]
Unless community pool is allocated an _exact number_ in which case I think the fix is likely trivial

**Comment by the-frey** [comment]
Ah no wait, I've got it backwards 'cos accounts coins exceeds supply, my bad.

**Comment by the-frey** [comment]
Okay, maybe try the genesis on this branch? Not sure if `supply` needs to be set as well as the community pool config param, but we can remove if it's not needed https://github.com/CosmosContracts/testnets/tree/community_pool

**Comment by the-frey** [comment]
@JakeHartnell what command were you running when it threw that error? I'll try & replicate and then test this fix locally.

**Comment by JakeHartnell** [comment]
This comment from @dfadeev was helpful: https://github.com/CosmosContracts/Juno/issues/15#issuecomment-860249934

Supply was not being set `"supply": []`

Setting it to:
```
"supply": [
        {
          "denom": "ujuno",
          "amount": "72819737204316"
        }
      ],
 ```
Seems to have done the trick.

Of course, I just manually edited this. Would be nice if the code that generates the airdrop Genesis added this... or at least update the instructions.

**Comment by the-frey** [comment]
I'll take a look after dinner. IIRC all those values are availabile at the time the `juno_out.json` file is written by the airdrop code, so should be simple enough to do (hopefully)

**Comment by faddat** [comment]
@JakeHartnell I'm going to keep working on the "code" version but also think we should put up a testnet with your manually repaired file.

**Comment by JakeHartnell** [comment]
> @JakeHartnell I'm going to keep working on the "code" version but also think we should put up a testnet with your manually repaired file.

:100:
