### ISSUE TITLE
Can not starting th node

### ISSUE THREAD

**Issue by malingzhao** [CosmosContracts/juno#160]
g crisis invariants inv=0/11 module=x/crisis name=distribution/nonnegative-outstanding
3:57PM INF asserting crisis invariants inv=1/11 module=x/crisis name=distribution/can-withdraw
3:57PM INF asserting crisis invariants inv=2/11 module=x/crisis name=distribution/reference-count
3:57PM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/module-account
3:57PM INF asserting crisis invariants inv=4/11 module=x/crisis name=staking/module-accounts
3:57PM INF asserting crisis invariants inv=5/11 module=x/crisis name=staking/nonnegative-power
3:57PM INF asserting crisis invariants inv=6/11 module=x/crisis name=staking/positive-delegation
3:57PM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/delegator-shares
3:57PM INF asserting crisis invariants inv=8/11 module=x/crisis name=bank/nonnegative-outstanding
3:57PM INF asserting crisis invariants inv=9/11 module=x/crisis name=bank/total-supply
3:57PM INF asserting crisis invariants inv=10/11 module=x/crisis name=gov/module-account
3:57PM INF asserted all invariants duration=181.496891 height=0 module=x/crisis
panic: commission can't be lower than 5%: unauthorized

**Comment by the-frey** [comment]
Your problem is listed in the stacktrace. `panic: commission can't be lower than 5%: unauthorized`

**Comment by TrevorJTClarke** [comment]
Hi @the-frey can you explain the solution for this? I see a lot of people having this issue for New nodes/RPCs in discord (See attached screenshots with scenarios).

I believe myself (and many other captured here) are having issues trying to sync using the latest v6, from snapshots graciously available from polkachu. 
Looks like @nullmames kindly put a list together of the direct sync path - which has been extremely hard to nail down from the various sources this data exists, not to mention not living in the docs.

For an RPC node, trying not to get hit with the 'commission' settings, is this path correct:
Image here contains the needed upgrade path, and an RPC node needs to sync from recent genesis?
<img width="685" alt="Screen Shot 2022-05-27 at 4 40 18 PM" src="https://user-images.githubusercontent.com/2633184/170800893-a251dd86-694e-49cd-a321-e2b8652d26b1.png">

If I'm getting it wrong, please correct me. Lots of time trying to put the pieces together, with an ultimate goal of better documentation contribution if all works.
Appreciate it!

Screenshot references:
<img width="667" alt="Screen Shot 2022-05-27 at 4 37 58 PM" src="https://user-images.githubusercontent.com/2633184/170800840-a4bd1491-636a-4b5d-8cff-2c459601221d.png">
<img width="681" alt="Screen Shot 2022-05-27 at 4 38 08 PM" src="https://user-images.githubusercontent.com/2633184/170800843-da4e2d41-7cec-41d5-93c6-0d55479b1ec8.png">
<img width="684" alt="Screen Shot 2022-05-27 at 4 39 55 PM" src="https://user-images.githubusercontent.com/2633184/170800845-a07bebcc-6ba9-4323-b164-96576b7272e3.png">

**Comment by nullmames** [comment]
Hi @TrevorJTClarke 

This is totally my fault. It has been a hectic few months and a lot has changed. I will commit to building and testing a node TODAY and updating the docs with a known working configuration for both sync from genesis for the current "Phoenix" mainnet as well as a shortcut from a snapshot. I will also commit to make sure this is updated within a week of any future upgrades. 

Again, my apologies. 🙏

**Comment by TrevorJTClarke** [comment]
Hey @nullmames no worries at all here - again just trying to raise the issue :D 

Appreciate your time in the replies everywhere!!
If you need/want help in doing so, couple people on standby for you. Happy to help during or once your piece is done.

TYSM!! 😻

**Comment by nullmames** [comment]
@TrevorJTClarke it would be great if you could try the instructions after they are comete to confirm

**Comment by TrevorJTClarke** [comment]
@nullmames just ping, were ready

**Comment by nullmames** [comment]
@TrevorJTClarke 

If you follow these instructions you should be up on mainnet in no time.

https://docs.junonetwork.io/validators/sync-from-snapshot

**Comment by nullmames** [comment]
Have also added "Mainnet Upgrades" page to step through all upgrades to date.

https://docs.junonetwork.io/validators/mainnet-upgrades

**Comment by nullmames** [comment]
@TrevorJTClarke were you able to sync using these instructions?

**Comment by sascha1337** [comment]
gb ram ~ 32 or 64 bare metal ?

**Comment by nullmames** [comment]
> gb ram ~ 32 or 64 bare metal ?

32 is plenty
