### ISSUE TITLE
5% minimum validator comission

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#17]
This leads to a healthier network that is more difficult to capture, so I think we should get this in before cutting mainnet.

**Comment by blockcreators** [comment]
So it looks like the community poll has changed back to 2.5%
Perhaps it can start with this, and a governance proposal can be put up after launch.

**Comment by faddat** [comment]
Kinda good with just going with 5%.

But let's see.  I won't get this in till some time next week anyhow.

**Comment by faddat** [comment]
I need to either get osmo's minimum commission into the comsos-sdk or we use the osmo fork.

**Comment by faddat** [comment]
You know I should try to squeeze this one in I think it will improve the quality of the network and won't be difficult #43

**Comment by nullmames** [comment]
i am all for this. i noted there are already gentx submissions with 0% commissions

**Comment by nullmames** [comment]
at the risk of an infinite loop
https://www.mintscan.io/juno/proposals/3

**Comment by leha2148** [comment]
@faddat the vote was accepted, but what will happen to the validators who set the maximum commission less than 5%, they will not be able to raise it? maybe give them the opportunity to do it 1 time?

**Comment by nullmames** [comment]
@leha2148 the minimum commission will be introduced with the upcoming moneta upgrade. this means that any validator with less than 5% commission before the upgrade will have 5% commission after the upgrade, automatically.

**Comment by the-frey** [comment]
Right so to implement this we need:

- [ ] Param change
- [ ] Upgrade handler

Anything else? Could use clarifying here so that it can be implemented

**Comment by giansalex** [comment]
This is done
