### ISSUE TITLE
more composable/interoperable protos

### ISSUE THREAD

**Issue by pyramation** [CosmosContracts/juno#202]
Hello! I'm working on tooling to generate clients, and it seems that juno doesn't do what others are doing for storing the proto files.

For example,

- [./proto/stargaze](https://github.com/public-awesome/stargaze/tree/main/proto/stargaze)
- [./proto/osmosis](https://github.com/osmosis-labs/osmosis/tree/main/proto/osmosis)
- [./proto/akash](https://github.com/ovrclk/akash/tree/master/proto/akash)
- [./proto/cosmos](https://github.com/cosmos/cosmos-sdk/tree/main/proto)

To make this more interoperable, can we move [./proto/mint/](https://github.com/CosmosContracts/juno/tree/main/proto/mint) so it's `./proto/juno/mint`?

It looks like a pretty small change, but would be HUGE in terms of interoperability.

**Comment by pyramation** [comment]
@faddat @JakeHartnell should be small change? I already tested in my local client and works great if we do something like this https://github.com/pyramation/protobufs/commit/53394ed2d9654b36cee4263de7c5b8e972680e69

**Comment by faddat** [comment]
I would be delighted to take care of this right now :-)

**Comment by sascha1337** [comment]
LGTM - consistency is super important

**Comment by faddat** [comment]
That it is. 

I'm working on adding a formal protobufs generation process to juno, it is based on this PR:

https://github.com/osmosis-labs/osmosis/pull/1455/

I'd rather use `buf`

**Comment by sascha1337** [comment]
I've got some go-protobuf to typescript d.ts scripts laying around - 
is anything like this already implemented, yet ?

**Comment by faddat** [comment]
https://github.com/faddat/archlinux-docker/actions/runs/2350303058

That's the new development environment being built, which includes buf

**Comment by pyramation** [comment]
> I've got some go-protobuf to typescript d.ts scripts laying around - is anything like this already implemented, yet ?

yea telescope is what I'm referencing for this issue, it codegens a TS library with clients loaded with types and amino messages,  https://github.com/osmosis-labs/telescope

**Comment by faddat** [comment]
https://github.com/cosmos/cosmos-sdk/issues/12150
