### ISSUE TITLE
mimalloc

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#220]
I'm going to do an evaluation of mimalloc, and have a little fun / trial something that I'd like to deploy more widely in cosmos.

5x junos one for each database type
state synced in ci

times

1 of each without mimalloc and 1 of each with

the same setup will allow us to distribute docker images that automatically state sync so that we can improve our network-wide usage of Akash for RPCs.

**Comment by sascha1337** [comment]
for wasm contracts, would this https://github.com/rustwasm/wee_alloc thing here make sense, or rather less - i did not see much difference, when i made some quick tests including this one to cw-** crate builds. 

thanks fad!

**Comment by faddat** [comment]
Wow hey listen I don’t know but I guess this is another thing to try

**Comment by faddat** [comment]
I no longer think this is really worth tracking. If anybody does, please reopen it.
