### ISSUE TITLE
🐍 Install Snyk

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#221]
Could our dear repo owner -- iirc @blockcreators -- please install Snyk?

It is a security scanning github action that will report privatey, so it needs a secret put in our repository.

Cheers!

**Comment by sascha1337** [comment]
@blockcreators _followup_ - would be great to get Snyk up
did you try to do so yet?

btw: its possible to let snyk scan public repositories, even without access, and it straight raised some complains regarding security - its just influxdb dep, but i love the breakdown view


![Screen Shot 2022-06-02 at 8 13 06 PM](https://user-images.githubusercontent.com/12372821/171626682-31e6f5b9-453c-44d6-be22-de02af434215.png)
