### ISSUE TITLE
Upgrade to 0.43.0 when starport does

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#23]
Seems to me that this release is well worth waiting for:

https://github.com/cosmos/cosmos-sdk/releases/tag/v0.43.0-rc0

https://github.com/tendermint/starport/issues/1307

**Comment by faddat** [comment]
Hey I wanted to jump in and offer an update here. Currently I am updating starport to version 0.42.8.

After that, 0.43.0.

There are some great improvements to how starport handles wasm.

**Comment by faddat** [comment]
@romelukaku helped me with 0.43.0 for https://github.com/faddat/dig

Have run a few small testnets of that and will do a larger one this weekend.  

I am also going to try and figure out how to get this into Starport.

**Comment by giansalex** [comment]
Fyi https://github.com/CosmWasm/wasmd/issues/501

**Comment by faddat** [comment]
Now that I failed at upgrading to 0.43.0, succeeding at it should be much easier :P
