### ISSUE TITLE
ICS Functionality for Juno (tracking issue for discussion)

### ISSUE THREAD

**Issue by the-frey** [CosmosContracts/juno#233]

**Comment by faddat** [comment]
Do we want to pursue this?

I know how to give Juno ICS functionality but it does seem to at this time restrict us to using SDK 45.

**Comment by the-frey** [comment]
I'm not sure ICS is on the cards. My money is probably on smart contract based mesh security. Thoughts @JakeHartnell / @dimiandre ?

**Comment by Reecepbcups** [comment]
Is this in regards to Interchain security v1/v2/v3? If so we are going the mesh way - this issue can be closed if so

**Comment by JakeHartnell** [comment]
> I'm not sure ICS is on the cards. My money is probably on smart contract based mesh security. Thoughts @JakeHartnell / @dimiandre ?

Mesh Security > Replicated Security.
