### ISSUE TITLE
Add liquid staking module (discussion)

### ISSUE THREAD

**Issue by the-frey** [CosmosContracts/juno#234]
AFAIUI we need to include this in order to have Quicksilver liquid staking work without unbonding times https://github.com/iqlusioninc/liquidity-staking-module

**Comment by faddat** [comment]
I think that we should write the code, then make the gov prop.

**Comment by the-frey** [comment]
Yeah I think there's a second thing which is AFAIUI we need an ICQ impl for this to work, so we need to land on one of those as well.

**Comment by faddat** [comment]
This remains a challenging moving target.

**Comment by faddat** [comment]
This feature did not even make it into SDK-47.

We would be waiting until at least SDK 48 unless we want to only add the module and then being able to safely add it begins with our adoption of SDK 46.

The only other choice is to add support to the LSM itself for 47.
