### ISSUE TITLE
Seperation of normal TX from Contract Deployment TX

### ISSUE THREAD

**Issue by blockcreators** [CosmosContracts/Juno#25]
There seems to be the potential that someone could set up a validator, set the upload fee to 0 (or cheap) and then after the spam uploading of bulk contracts happen, they could shut down their validator and move on (not have to deal with the shared load of storage costs.

I am trying to figure out if having a separate cost structure for the TX and the Contract Deployment transaction might be beneficial to avoid this. For the Contract Deployment transaction the validators could somehow agree on a shared minimum amount per contract byte size? This might prevent renegade spam validators from emerging?

**Comment by blockcreators** [comment]
So is the cost of a normal transactions based on the transaction data size currently? If so then we would just need to worry about setting a minimum TX cost (based on data size) and let the validators agree on what that should be. And if we could automate this it would be great?

**Comment by jotcodeofficial** [comment]
will revisit in v2

**Comment by blockcreators** [comment]
We can re-visit in v2
