### ISSUE TITLE
Inflation module

### ISSUE THREAD

**Issue by dimiandre** [CosmosContracts/Juno#27]
Need to develop a custom minting/inflation module that fit juno tokenomics details

**Comment by blockcreators** [comment]
**Reward Schedule**

**Phase 1:** Fixed inflation 40%
New Juno in year 1 = (+25.961.297)
Supply after year 1 = 90.864.540 $JUNO
**Phase 2:** Fixed inflation 20%
New Juno in year 2 = (+18.172.908)
Supply after year 2 = 109.037.449 JUNO
**Phase 3:** Fixed inflation 10%
New Juno in year 3= (+10.903.744)
Supply after year 3 = 119.941.194 JUNO

Once the inflation reaches 10% it gradually reduces on a fixed 1% basis each year.

Phase 4 = Fixed 9% (+10.794.707) Supply = 130.735.901 JUNO
Phase 5 = Fixed 8% (+10.458.872) Supply = 141.194.773 JUNO
Phase 6 = Fixed 7% (+9.883.634) Supply = 151.078.407 JUNO
Phase 7 = Fixed 6% (+9.064.704) Supply = 160.143.112 JUNO
Phase 8 = Fixed 5% (+8.007.155) Supply = 168.150.267 JUNO
Phase 9 = Fixed 4% (+6.726.010) Supply = 174.876.278 JUNO
Phase 10 = Fixed 3% (+5.246.288) Supply = 180.122.566 JUNO
Phase 11 = Fixed 2% (+3.602.451) Supply = 183.725.018 JUNO
Phase 12 = Fixed 1% (+1.837.250) Supply = 185.562.268 JUNO

**Comment by giansalex** [comment]
@blockcreators must there be new parameters for Gov?

**Comment by Wolfcontract** [comment]
> @blockcreators must there be new parameters for Gov?

Yes but the governance module is separate. First we need to put the reward schedule in stone. Has to be set in a way that exact numbers are met that are pre-calculated ie similar to what Osmosis is doing with their daily epoch distribution.

**Comment by blockcreators** [comment]
We need to decide is the Osmosis epoch system better or worse for implementing the token inflation schedule that we want.
Whichever way is easier to code and reason with I am in favor of.
