### ISSUE TITLE
The Bitcoin Flaw: Juno's Mint Module Upgrade 

### ISSUE THREAD

**Issue by waspcartel** [CosmosContracts/juno#271]
Some thoughts on Juno and how to increase its value and efficiency going forward, from Notional Labs: 

Juno's mint module (https://github.com/CosmosContracts/juno/tree/main/x/mint) functions similar to Bitcoin, with routine halvings. 

1. This should be replaced with a gradient using an epochs model. The gradient would be addressed every 1,000 wall-clock ⏰ seconds. The halving code is sub-par and we should remove it. We would put this through governance before making an adjustments. 

2. We want to change the block heartbeat so even if there are no transactions, a block is still produced around every three minutes.
 
3. We want to reduce the max block time to sub-1-second and ideally as fast as possible. We also want to move from a step function to a gradient. 

4.  PebbleDB should be default. 

5. Native minimum commissions: SDK 0.46.0 has minimum commission by default, so all the Juno min. commission code can be removed - although we'll likely need to use update handlers. 

All of this will increase the value of Juno.

**Comment by faddat** [comment]
This has been addresed by @dimiandre in #273
