### ISSUE TITLE
Getting  Generic error: Querier contract error: codespace: wasm, code: 9: execute wasm contract failed

### ISSUE THREAD

**Issue by sbnair** [CosmosContracts/juno#275]
I am using this code : deps.querier.query_wasm_smart to query from smart contract and it works perfectly with junod command but in rust when i try to query with the same contract address i get this error, pls let me know what could be the cause of this. 
Generic error: Querier contract error: codespace: wasm, code: 9: execute wasm contract failed

Thanks.

**Comment by the-frey** [comment]
Hi, this is a contract-level question, so please ask on the Juno dev Discord or CosmWasm Discord with a reproducible code example. Thanks 👍
