### ISSUE TITLE
Kwallet keyring backend not working

### ISSUE THREAD

**Issue by Buckram123** [CosmosContracts/juno#277]
For some reason not fixed for me https://github.com/cosmos/cosmos-sdk/issues/9562

### Version
junod: v9.0.0
kwallet: 5.97.0-4
OS: Arch Linux

### Reproducing
1. Have junod connected to the kwallet
2. `junod keys add bob`

### Error
```
Error: unexpected end of JSON input
```

getting same error on wasmd 0.16.0

Changing keyring to gnome-keyring helps, but I think kwallet is still preferred for KDE users

**Comment by dimiandre** [comment]
Is that a fresh Linux installation? We changed structure of keys with v9, if you had keys in v8 and didn't migrate you get that error

**Comment by Buckram123** [comment]
> Is that a fresh Linux installation? We changed structure of keys with v9, if you had keys in v8 and didn't migrate you get that error

Yeah, fresh, no migration involved

**Comment by Buckram123** [comment]
Fixed in v10.0.2
