### ISSUE TITLE
Change contract CI to be inside this repo

### ISSUE THREAD

**Issue by the-frey** [CosmosContracts/juno#288]
This one is a note to self to have a think about.

Currently, code is pulled in from tags elsewhere and compiled. It probably makes more sense to just compile elsewhere and bring the wasm binaries straight inside this repo.

Pros:
- everything in one place
- quicker to change when things go wrong and need updating

Cons:
- harder to audit
- no way of seeing direct provenance of binary (might be an issue for e.g. unity prop?)

**Comment by faddat** [comment]
Hi, just so you know I would prefer to actually move the source code here that way we're not dealing with binaries from elsewhere. This increases the visibility of the code.

**Comment by Reecepbcups** [comment]
This has been completed in the SDK v47 PR as well as some others

47 - https://github.com/CosmosContracts/juno/pull/646 

https://github.com/CosmosContracts/juno/pull/679

https://github.com/CosmosContracts/juno/pull/669

All contract CI is now in this repo & properly tested with ICtest with the merge of v47 :partying_face:
