### ISSUE TITLE
Quick start front and center featuring state sync

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#29]
The Readme.md file should provide exact directions on how to state sync a juno node.

**Comment by giansalex** [comment]
there is an issue https://github.com/CosmWasm/wasmd/issues/478

**Comment by faddat** [comment]
post-mainnet

**Comment by the-frey** [comment]
This is due as part of `v2.0.0` - https://github.com/CosmWasm/wasmd/milestone/17

**Comment by the-frey** [comment]
I believe @giansalex has now got PRs in for this?

**Comment by giansalex** [comment]
i think after moneta upgrade

**Comment by giansalex** [comment]
feature is included in [cosmos-sdk v0.45.2](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.2), now we have to add support for x/wasm

**Comment by giansalex** [comment]
> https://medium.com/cosmwasm/wasmd-0-27-released-57cc7dd754a6
> 
> wasmd update supports state sync now

yes, i will send a pull request
