### ISSUE TITLE
The juno version of  v9.0.0  crashed in the middle of night

### ISSUE THREAD

**Issue by Liamlu28** [CosmosContracts/juno#296]
Hi team. I received an alarm in the middle of the night that Juno service had been down. This version is v9.0.0. Do upgrades have to be done within 24 hours? I updated version v.10.0.2 and found some errors in the Juno log. Thanks

```shell
NodePing Alert
APP  [20 minutes ago]
Host Juno : HTTPADV is back up after being down for  7 hours 5 minutes as of Thu Sep 29 2022 09:16:20 GMT+1200.
```
![image](https://user-images.githubusercontent.com/3294496/192893996-23367996-02a4-4c65-be23-d478cc24db7b.png)

**Comment by the-frey** [comment]
There was an upgrade via gov proposal, yes. Closing as this is not an issue with the binary.
