### ISSUE TITLE
Tracking issue for V11

### ISSUE THREAD

**Issue by the-frey** [CosmosContracts/juno#302]
Currently, V11 is slated to be a minor, but consensus-breaking release. 

It will include:
- [x] wasmd 0.29
  - [x] wasmvm 1.1
- [x] SDK 45.8
- [x] IBC 3.3

As some of these have bugfixes, the goal will be to ship this ASAP and then move on to V12 for larger ferature work.

**Comment by the-frey** [comment]
#313

**Comment by Luther0123** [comment]
@the-frey visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by vuong177** [comment]
Ready to v12 !
