### ISSUE TITLE
Oracle on Juno

### ISSUE THREAD

**Issue by vuong177** [CosmosContracts/juno#308]
This issue is to gather ideas about implementing a  Oracle price feed for Juno.
Several Oracle implementations in Cosmos already exist.
It is divided into 2 main approaches:

- Build a module for oracle, we can refer to x/oracle of Terra and Kujira.
- Build a smart contract.

**Comment by vuong177** [comment]
Oracle module in Umee/Kurijra chain is a good reference.

**Comment by vuong177** [comment]
We also need a front-end to track validator status of oracle. This field needs to track :
 - The current miss counter for a given validator address
 - The current slash window progress
 - The outstanding oracle aggregate votes/prevotes
 - Module param.

**Comment by Reecepbcups** [comment]
@vuong177 - I have built a discord bot to do this, will also do a website after up on Uni next week
