### ISSUE TITLE
proposal: introduce an e2e test suite

### ISSUE THREAD

**Issue by vuong177** [CosmosContracts/juno#317]
Refer to the e2e test in osmosis and Gaia. I propose we should introduce an e2e integration test suite that allows us to test chain functionality  :
  - IBC transfers
  - Chain upgrade
  - Interact with Wasm Contract 
 
We can refer to Osmosis and Gaia  : 
  - https://github.com/cosmos/gaia/tree/main/tests/e2e
  - https://github.com/osmosis-labs/osmosis/tree/main/tests/e2e

**Comment by the-frey** [comment]
I like the idea of having e2e tests that allows us to check IBC/chain upgrades for sure.

**Comment by vuong177** [comment]
yes, my thought was to create a LocalJuno (a testnet with the current mainnet state) and will make a chain upgrade on it.

**Comment by Luther0123** [comment]
Visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)
