### ISSUE TITLE
Disable CosmWasm module for mainnet

### ISSUE THREAD

**Issue by blockcreators** [CosmosContracts/Juno#32]
Disable CosmWasm module for mainnet

**Comment by faddat** [comment]
Wat?

**Comment by giansalex** [comment]
Or revert this commit https://github.com/CosmosContracts/Juno/commit/f0a3dfe9527b2076509c1f8f6186569787572265

**Comment by faddat** [comment]
Reverting the commit won't work well (history of the repo)

So I re-scaffolded again

oh, right the other thing....

**Comment by faddat** [comment]
suggest #42 ; it removes:

* wasm
* /x/juno

while getting us all of the new-starport-hotness.

Also it does not break @giansalex's work :P

**Comment by faddat** [comment]
This is closed by #45

**Comment by giansalex** [comment]
I believe that was solved in #42

**Comment by faddat** [comment]
Yeah that's correct It's done
