### ISSUE TITLE
Global fee module [v46/v47 sdk]

### ISSUE THREAD

**Issue by Reecepbcups** [CosmosContracts/juno#327]
**note: postponing until juno moved to v46/47 so we can import from gaia directly**

A way to set a minimum global fee via governance param for different tokens, this is NOT going to be in SDK47

Ex: force all nodes to use 0.025ujuno as a fee. 
Can use as many token denoms here as you want (including ibc). 

Default genesis is empty array, param change to update
If the fee token is less than the globalfee, the Tx fails for not enough fee

**Comment by Luther0123** [comment]
Hi @Reecepbcups visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)
