### ISSUE TITLE
Token Factory Convert Tools

### ISSUE THREAD

**Issue by Reecepbcups** [CosmosContracts/juno#334]
Dec-7-2022 meeting notes: https://hackmd.io/@reecepbcups/cw20-to-tokenfactory

In many ways a lot better than current CW20 implementation, especially with bank query and Developer UX
_Needed for UltraSoundJuno project as well_
<br/>

Apart of this, we should write scripts / documentation on converting CW20s to the native factory.
- [Airdrop Style](https://github.com/Reecepbcups/cw20-to-native)
- [CW20 Burn Contract (send from balance & mint options)](https://github.com/Reecepbcups/cw20-tokenfactory-burn)
- CW20 impl the tokenfactory interface (native bank query and mint)
- others?
- https://github.com/CosmosContracts/tokenfactory-contracts
<br/>

- Question is best approach for JunoSwap as well for already public CW20 tokens if they do move to native

- Taking into account dao governance CW20 tokens

**Comment by mccallofthewild** [comment]
(DRAFT) Other considerations: 

### IBC fungibility
cw20 tokens are transferred over the cw20-ics20 contract address port so their IBC denominations will not be fungible with token factory tokens transferred over the transfer port. There will eventually be token naming services to handle this, but for the time being it puts the migration issue back to square one.
https://github.com/CosmWasm/cw-plus/blob/main/contracts/cw20-ics20/

**Comment by Reecepbcups** [comment]
@mccallofthewild This would just require the given token to be transferred back to the native chain to redeem correct?

If a CW20 token had been moved chains, It’s best to go with option 2 (1 for 1 burn on native chain). Since the ibc denom will change back to native

**Comment by the-frey** [comment]
Given that a CW20 using-service has to specifically integrate the tokenfactory hooks isn't this more up to implementers? i.e. those that haven't yet launched can use tokenfactory and those that are already live have to work out a migration strat if they want to use it && doubly so if they already have tokens in the wild over IBC

**Comment by mccallofthewild** [comment]
@Reecepbcups they would actually just need return them from osmosis then send them back out over the `transfer` port. the cw20 would have the cw20-ics20 contract address stored in its balances. no burn needed 👍

**Comment by mccallofthewild** [comment]
@the-frey for sure. we are doing a bit of brainstorming to figure out if we can make the migration process any easier without a lot of effort. it would be cool to have one token standard on juno.

**Comment by Reecepbcups** [comment]
This has been completed with juno.reece.sh. Next step is getting into DAODAO
