### ISSUE TITLE
`junod`'s `--height` flag seems to have issues now

### ISSUE THREAD

**Issue by mikedotexe** [CosmosContracts/juno#344]
#### Specifications

Juno version: `v11`, also `10.1.0`
OS & Version: OSX

#### Expected behaviour

The `--height` flag should allow us to check details at a given block height

#### Actual behaviour

This error:

>Error: rpc error: code = InvalidArgument desc = contract: not found: invalid request

#### Steps to reproduce the behaviour

Note that this works…
without `--height`:
(works)
`junod q wasm contract-state smart juno1h8t6uhqukwgp4qn0nf6h9j93zu4z57rjlzp0x00qrnu4lmnfw9tsjas2g6 '{"get_tasks":{}}' --node https://juno-testnet-rpc.polkachu.com:443 --chain-id uni-5 -o json | jq`

same command with `--height`:
`junod q wasm contract-state smart juno1h8t6uhqukwgp4qn0nf6h9j93zu4z57rjlzp0x00qrnu4lmnfw9tsjas2g6 '{"get_tasks":{}}' --height 5484637 --node https://juno-testnet-rpc.polkachu.com:443 --chain-id uni-5 -o json | jq`

**Comment by vuong177** [comment]
Because uni testnet has been restarted, current block in uni-5 is 585940.

**Comment by mikedotexe** [comment]
hey @vuong177 thanks for that. I think I have a better way to reproduce this…

Note that at the time of this writing, the latest block for Juno testnet is around 590,470

This works at height `530,000` :
`junod q wasm contract-state smart juno1h8t6uhqukwgp4qn0nf6h9j93zu4z57rjlzp0x00qrnu4lmnfw9tsjas2g6 '{"get_tasks":{}}' --height 530000 --node https://juno-testnet-rpc.polkachu.com:443 --chain-id uni-5 -o json | jq`

This doesn't work at height `530,600` (600 blocks "sooner", so you'd think it's not pruned):
`junod q wasm contract-state smart juno1h8t6uhqukwgp4qn0nf6h9j93zu4z57rjlzp0x00qrnu4lmnfw9tsjas2g6 '{"get_tasks":{}}' --height 530600 --node https://juno-testnet-rpc.polkachu.com:443 --chain-id uni-5 -o json | jq`

Second one errors with:
> Error: rpc error: code = InvalidArgument desc = contract: not found: invalid request

**Comment by vuong177** [comment]
@mikedotexe thank you for your help. I'm digging into it.

**Comment by the-frey** [comment]
Are you expecting it to return any data? All three of those return for me, except with `data: []` as the response.

Note: I used a different RPC (local one on a val box)

**Comment by vuong177** [comment]
@mikedotexe maybe the node for `https://juno-testnet-rpc.polkachu.com:443` is a pruning node, so you can't query the old height.

**Comment by mikedotexe** [comment]
> Note: I used a different RPC (local one on a val box)

Interesting, maybe it is polkachu's testnet RPC. Just very strange that it pruned state _after_ a block height that returned properly. Sounds like this is an RPC issue instead of one for this repo. Feels like it's a good time to close it. Thank you both!
