### ISSUE TITLE
[CI] Update GitHub Action to push docker images

### ISSUE THREAD

**Issue by anhductn2001** [CosmosContracts/juno#371]
## Background

 Updates the GitHub Actions CI to push docker images due to the deprecation of set-output commands in Github Action (source: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

The functionality's still the same.

## Suggested Design

 Update GitHub action logic
 Rename it to push-docker-images.yaml

## Acceptance Criteria

- all existing and new tests should pass

**Comment by faddat** [comment]
great idea
