### ISSUE TITLE
Tracking issue for Juno v13

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#373]
- [ ] SDK v47
  - https://github.com/CosmWasm/wasmd/pull/1132
  - https://github.com/cosmos/interchain-accounts-demo/pull/165
    - this is the current high priority item @vuong177 
  - https://github.com/cosmos/ibc-go/pull/2955

Summary of 47:

* Confio working on 47 in a feature branch and intends to have support as a feature branch going forward.

* afaik, 47 doesn't have the liquid staking module, meaning the best course of action is to upgrade it to 47 also

*

Other:
- [ ] https://github.com/CosmosContracts/juno/issues/234

Need feedback on the scope of v13.  Basically, not sure if we want to target:

* sdk 47 -  and have some upstream timeline questions
* sdk 46 -  and be using eve's forked modules

**Comment by Reecepbcups** [comment]
Oracle will be in v12, and LocalJuno/IBCtest will be between now and v13. Not required for version change

So new list is:
- v47 bump (ibc + wasm)
- https://github.com/CosmosContracts/juno/issues/234
- globalfee
- feesplit module?

**Comment by faddat** [comment]
Closing in favor of #475
