### ISSUE TITLE
Enhance Local Juno for CI / Custom testing

### ISSUE THREAD

**Issue by apollo-pablo** [CosmosContracts/juno#380]
## Background

We would like to know if possible Running `local Juno` with `predefined accounts` and `possibility to tuneup configuration` for CI or integration-test running docker containers, similar like [local-osmosis](https://github.com/osmosis-labs/LocalOsmosis) or [local-terra](https://github.com/terra-money/LocalTerra) with a lightweight database.

## Suggested Design

Some like those projects mention up.

## Acceptance Criteria

- [ ] Should allow to customize app.toml, client.toml and config.toml.
- [ ] Should have predefined accounts like [mnemonics.json](https://github.com/osmosis-labs/LocalOsmosis/blob/main/mnemonics.json) so the CI can have private keys to genereate SignedKeys that allow to operate with those testing accounts

**Comment by vuong177** [comment]
https://github.com/CosmosContracts/juno/pull/322

@apollo-pablo we have a PR here

**Comment by vuong177** [comment]
mnemonics are defined by this : https://github.com/CosmosContracts/juno/blob/55d931d70078acf3988a3d17042103103baa70ce/tests/localjuno/scripts/add_keys.sh#L13

**Comment by anhductn2001** [comment]
Hey @apollo-pablo, I think the current design of local-Juno is similar to local- Osmosis. We already have predefined accounts and possibility to tuneup configuration for running docker containers. You can read the changes in PR #322 and we can close this issue.
