### ISSUE TITLE
[v12] Packet Forward Middleware

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#419]
## Background

The packet-forward-middleware module in use on Gaia allows us to forward IBC packets to other chains (kinda makes us a router for ibc packets)

## Suggested Design

* bump packet-forward-middleware to ibc v4
* implement as in gaia

## Acceptance Criteria

* passes tests in Juno
* doesn't cause problems with wasm

**Comment by udit-gulati** [comment]
Hi @faddat @vuong177, can I work on this?

**Comment by jackzampolin** [comment]
We have a v5,6 branch and a v4 branch should be trivial. We have an existing test that shows gaia support 

https://github.com/strangelove-ventures/ibctest/blob/main/examples/ibc/packet_forward_test.go

**Comment by faddat** [comment]
Yeah that's what I thought Jack. Also @udit-gulati  if you want to work on it please do.  Thank you so much for that.

:)

**Comment by faddat** [comment]
https://github.com/strangelove-ventures/packet-forward-middleware/pull/45
