### ISSUE TITLE
Logic UpdateFeeShare not correct

### ISSUE THREAD

**Issue by GNaD13** [CosmosContracts/juno#429]
Logic UpdateFeeShare not correct

Currently, the UpdateFeeShare not working (bug in logic) https://github.com/CosmosContracts/juno/blob/7c6c26692bc03711382dbac271e9163ceb8ba6a0/x/feeshare/keeper/msg_server.go#L145-L173
What we need here is replace `feeshare.WithdrawerAddress` with `msg.WithdrawerAddress`. But currently, the code get the `withdrawAddr` from `feeshare.WithdrawerAddress` https://github.com/CosmosContracts/juno/blob/7c6c26692bc03711382dbac271e9163ceb8ba6a0/x/feeshare/keeper/msg_server.go#L156
and just re-add the `feeshare.WithdrawerAddress` with the `withdrawAddr` => No changed
https://github.com/CosmosContracts/juno/blob/7c6c26692bc03711382dbac271e9163ceb8ba6a0/x/feeshare/keeper/msg_server.go#L172

**Comment by faddat** [comment]
ah OK please fix this and -- **great find**!
