### ISSUE TITLE
Lint a second path or use go workspaces for price feeder

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#467]
The oracle module introduces a second go.mod file in the `price-feeder` folder.

We should either explicitly add the price-feeder folder to the linter, or begin using go workspaces.

Since go workspaces (go.work) has significant tradeoffs, we should.... flip a coin?

**Comment by Reecepbcups** [comment]
Just adding the folter to the linter is the better option here imo

**Comment by faddat** [comment]
Thank you I'll take care of that shortly
