### ISSUE TITLE
Releases: include binary + checksum

### ISSUE THREAD

**Issue by 08d2** [CosmosContracts/juno#476]
Releases such as [v11.0.3](https://github.com/CosmosContracts/juno/releases/tag/v11.0.3) should include compiled binary assets for supported platforms, ideally with checksum files for verification.

**Comment by faddat** [comment]
Why?

**Comment by 08d2** [comment]
> Why?
> 
> If binary then checksum, sure. But, I would like to know more about well realistically why binaries are needed even.

This is a confusing question. Source code at revision X does not reliably produce the same binary, compilation is subject to uncountably many properties of the build environment, each of which can potentially impact the behavior of the built artifact at runtime. The mapping between source code and built artifact is not 1-to-1. And since this project's deliverable is not source code, but rather an executable program, that program should be part of each release. Source code is insufficient.

**Comment by Reecepbcups** [comment]
Binaries are already provided (see v11.0.0) so much have been a bug with v11.0.3 hmm. Will add checksum for v12

**Comment by 08d2** [comment]
Oh cool, great! Thank you.

**Comment by 08d2** [comment]
Still need the artifacts on 11.0.3.

**Comment by Reecepbcups** [comment]
> Still need the artifacts on 11.0.3.

It does not run for previous, only new ones. I'll see if I can manually add tomorrow

**Comment by Reecepbcups** [comment]
@08d2 Added :)
