### ISSUE TITLE
Upgrade SDK to .44

### ISSUE THREAD

**Issue by blockcreators** [CosmosContracts/juno#48]
Upgrade when also supported with wasm v1.
Is the issue with 43 also with 42?

**Comment by giansalex** [comment]
so we need to rollback sdk 0.43 upgrade , to support wasm v1 (0.42x) ,
 @dimiandre can you confirm?

**Comment by faddat** [comment]
complete. with #49 

@blockcreators -- my opinion:

It would make more sense to keep 0.44.0 and if need be, make the updates to wasm to support it.

**Comment by giansalex** [comment]
I think it depends on whether wasm v1 will support sdk 0.44 
https://github.com/CosmWasm/wasmd/issues/501#issuecomment-910287939

**Comment by giansalex** [comment]
😥 , so will Juno wait until wasm supports 0.44?
 ![image](https://user-images.githubusercontent.com/14926587/132103602-9a57b32a-a95f-4b11-9a08-45edcf2debbf.png)

**Comment by blockcreators** [comment]
> I think it depends on whether wasm v1 will support sdk 0.44
> [CosmWasm/wasmd#501 (comment)](https://github.com/CosmWasm/wasmd/issues/501#issuecomment-910287939)

We have decided to go ahead and support 0.44 for our release.
We will still wait for was v1, and then add what we need on top to try and keep it as close as possible.

**Comment by faddat** [comment]
safe to close.
