### ISSUE TITLE
E2E - speed up & fix fails

### ISSUE THREAD

**Issue by Reecepbcups** [CosmosContracts/juno#484]
1) no commit timeout for the docker container (variable), move to 500ms for blocks. Does this break relaying?

2) randomize ports so multiple running CIs don't conflict & cause a query fail on the machine (can't start bc port bind)

**Comment by faddat** [comment]
DId this work, or did it just magically fix itself?

**Comment by Reecepbcups** [comment]
> DId this work, or did it just magically fix itself?

I think it magically fixed itself... Which scares me even more haha
