### ISSUE TITLE
[V12] - Oracle Cleanup Needs

### ISSUE THREAD

**Issue by Reecepbcups** [CosmosContracts/juno#485]
# Needs
- [ ] #486
- [x] #487
- [ ] Link source for query contract
- [x] price-feeder/config.toml
- [x] #490 
- [x] #504 ? 
- [x] #503

# Notes

**config.toml**
~~- A ton of "provider timed out" spam in between broadcasting votes~~
   - this is due to rate limiting on the osmosis & juno REST side... cosmos infra is yuck

~~Does it need to query so often (once a second)? We only submit 1 time per 30. Wouldn't every 5 be enough? don't want Vals to get blacklisted~~ yes, yes it does. We can reduce to 2 times per block maximum, not worth the risk

**Comment by faddat** [comment]
Fantastic

**Comment by faddat** [comment]
@vuong177 wdyt?

I like the idea of querying less often

**Comment by Reecepbcups** [comment]
> I like the idea of querying less often
@faddat Just did about an hour of testing.Not worth the risk of querying less often. 

Also it queries sequentially which I did not expect. We can optimize by 100% (2 second queries) at the max, and this begins to miss some submits. Would need an overhaul to the feeder to run all queries at 1 time in parallel

**Comment by Reecepbcups** [comment]
Scrapped, not confident in it
