### ISSUE TITLE
Fix query contract (scripts/oracle/oracle_querier.wasm  `UnsupportedRequest`)

### ISSUE THREAD

**Issue by vuong177** [CosmosContracts/juno#486]
## Background
- We should build a new contract for stargate query in oracle.
 
## Suggested Design
- `oracle_querier.wasm` replaced with a new contract that supports stargate query.

## Acceptance Criteria
- All e2e test passed

**Comment by udit-gulati** [comment]
@vuong177 can I work on this?

**Comment by vuong177** [comment]
yep

**Comment by Reecepbcups** [comment]
Scrapped, team not confident in it
