### ISSUE TITLE
ACHTUNG: Before Uni, write a TokenFactory bindings test contract

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#498]
that's really all. 

Always good to have some tests.

**Comment by vuong177** [comment]
We have a e2e test for this, but need to re-write the TokenFactory test contract.

**Comment by vuong177** [comment]
Because we changed from wasmbinding in TF to using stargate query.

**Comment by vuong177** [comment]
duplicate https://github.com/CosmosContracts/juno/issues/486
