### ISSUE TITLE
Force tag(name) usage in PRs

### ISSUE THREAD

**Issue by Reecepbcups** [CosmosContracts/juno#519]
Easier to sort for future updates

Ex: feat(oracle)

No need for tags, just review / releases

**Comment by faddat** [comment]
What do you mean about tags?

**Comment by Reecepbcups** [comment]
@faddat Like feat(module), chore(price-feeder) etc.

Should add CI to ensure this happens. just to keep things more clean

**Comment by Reecepbcups** [comment]
not really a priority
