### ISSUE TITLE
Upgrade to latest SDK and iavl before V12 mainnet

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#520]
## Background

Will just be doing a version bump. Cosmo SDK 45.12 and iavl 0.19.5 release soon.

## Suggested Design

> Here, you can put concrete steps as to what to do next
> e.g.
> - create test file in...

## Acceptance Criteria

> Goals & criteria for success
> e.g.
> - all existing and new tests should pass

**Comment by Reecepbcups** [comment]
We should not do this unless we run these versions on testnet as well. 

If we have to do an -alpha2 makes sense
