### ISSUE TITLE
Juno-1 release shouldn't be juno-1

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#56]
We should cut another release:

* Juno-1 has outdated libs, corrected in #53 and #54 

Minimally, we need to merge both of those PR's to ship.

**Comment by faddat** [comment]
I do not think that the IBC 1.1.0 -> IBC 1.2.0 transition was benign, and honestly my spm patch was just a rapid hack (though it worked of course).

**Comment by KingDmoney** [comment]
Anyone Here Willing to help a hardwork 27year old man , that has 70$ LTC to his name !! Get guidelines of setting the properstuff up , thank you

**Comment by giansalex** [comment]
v1 was released, this is obsolete
