### ISSUE TITLE
Enforce min gas fee for all transactions

### ISSUE THREAD

**Issue by blockcreators** [CosmosContracts/juno#58]
Because smart contracts might use transaction information, we cannot just archive older chain states and start fresh.
So it might be good to have a minimum transaction fee. This would reduce spamming the chain with 0 fee transactions, thus filling up the chain state with useless transaction data.

**Comment by JakeHartnell** [comment]
Network was able to be brought down with an attack from a malicious smart contract. This needs to be done.

**Comment by blockcreators** [comment]
Would be ideal to have the fee as a parameter so that governance can auto change it via voting.

**Comment by faddat** [comment]
Hot

**Comment by the-frey** [comment]
Don't disagree about it being changed by governance, but if governance changes it to 0 for zone reason then the network is ☠️

**Comment by blockcreators** [comment]
> Don't disagree about it being changed by governance, but if governance changes it to 0 for zone reason then the network is ☠️

Governance could also vote to mint 1 trillionzillion coins and do the same thing :)

**Comment by the-frey** [comment]
This is superceded by https://github.com/CosmosContracts/juno/issues/82

**Comment by JakeHartnell** [comment]
> Network was able to be brought down with an attack from a malicious smart contract. This needs to be done.

In hindsight, not sure if this is needed. #82 should be enough. More risk from messing with this IMO.
