### ISSUE TITLE
installation error: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]

### ISSUE THREAD

**Issue by oussamahamdaoui** [CosmosContracts/juno#63]
Hello everyone, I tried installing juno on my mac it runs on macOS Monterey 12.0 and when run the make command I get the following error: 

`In file included from ../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:38:
../../go/pkg/mod/github.com/zondax/hid@v0.9.0/hidapi/mac/hid.c:693:34: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here`

**Comment by the-frey** [comment]
I think this is an issue with a dependency - https://github.com/zondax/hid
So a fix would need to be contributed there.
Looks like this also will affect the Cosmos SDK, but I can't see an issue there for it. 🤔 

Is this a warning, or an out-and-out error?
