### ISSUE TITLE
we should not delete branches

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#645]
Today I noticed that there are a total of 30 branches in the juno repository.  

There have been far more than 30 branches made here, some of them containing work that we would like to use, others represent historical work done.  I'd like to suggest that we please not delete branches in this repository.

**Comment by Reecepbcups** [comment]
These branches which I deleted had no value. Any branches which even had a chance of possible future work of value I left

It makes no sense to keep dead branches for things juno implemented in other branches or not adding at all for any reason in the future
