### ISSUE TITLE
x/burn 🔥

### ISSUE THREAD

**Issue by poroburu** [CosmosContracts/juno#647]
# `x/burn` 🔥

## Background

The Juno community wants a canonical burn process. Currently burning causes `x/mint` to redistribute burned amounts. 

> If we burn it the mint module would remint the amount and giving it to the stakers yes ? 

> thats how it currently works, the 2nd year would basically be longer and wouldnt end in october

## Suggested Design

`x/burn` module. The module has an address where tokens and other assets can be canonically burned.

## Acceptance Criteria

- [ ] PR with a sound and functional `x/burn` module.
- [ ] Signalling proposal accepted by governance that indicates the desire to declare a canonical burn address.

**Comment by Reecepbcups** [comment]
I think we can burn through a cosmwasm contract without it being distributed via the mint module (afaik)

**Comment by dimiandre** [comment]
> I think we can burn through a cosmwasm contract without it being distributed via the mint module (afaik) Will need to do testing
> 
> If not I can make an adminless contract as the burn contract with no execute msg's so it is not migratable?

Yes seems trivial to implement on a contract

**Comment by Reecepbcups** [comment]
Bumping to priority with recent balance DAO

https://twitter.com/dimiandre/status/1681578666772385792?s=20

1) A burn module with no logic other than the module account? This way its a source of truth for the burn address. This would not take away from total supply unless we pass to x/mint and subtract only on query? (just so we can do it in a way that does not delay halvaning). Just needs a simple query for how much the address has (just bank query tbh)

2) Smart contract which does nothing, maybe we can use instantiate2 to make it `juno1burn....` or something?

3) Generate a random account using a currently valid pub key address, get it to be `juno1burn...` then brute force / change the last 6 values of the addr to match the correct data

4) Not where where bank::burn actually sends it, if it is to an address we could see if we can block it from sending funds and so the mint module does not re-mint. Needs more research

**Comment by JakeHartnell** [comment]
Hot. 🔥
