### ISSUE TITLE
Enhance the LocalJuno environment

### ISSUE THREAD

**Issue by duguorong009** [CosmosContracts/juno#657]
## Description
 - Number of testing accounts embedded in LocalJuno is only 1
 - Use the denom `ucosm` for `fee` token in LocalJuno
 - Current chain ID of LocalJuno is `testing`
 
## Suggestion
 - I hope that the juno team adds more accounts in LocalJuno
   Over [here](https://github.com/CosmosContracts/juno/blob/main/docker/test-user.env) and [here](https://github.com/CosmosContracts/juno/blob/main/docker-compose.yml#L9), there is only 1 account.
   I think we can add more accounts(hopefully, 10 accounts like [osmosis](https://github.com/osmosis-labs/osmosis/tree/main/tests/localosmosis#localosmosis-accounts) or [terra](https://github.com/terra-money/LocalTerra#accounts)).
   They share the same mnemonics, and it could be applied here.
   
 - I hope that the juno team updates the `fee` token denom as `ujuno`
   I think it is better for developer experience.
   
 - I hope that the chain ID of LocalJuno is `localjuno`, not `testing`

**Comment by Reecepbcups** [comment]
Thanks for creating an issue! I have this in my todo and will be using interchain test + an explorer as well.

Will allow developers to run multiple nodes per network super easily + IBC relaying if desired

**Comment by duguorong009** [comment]
Thanks! @Reecepbcups 

> Will allow developers to run multiple nodes per network super easily + IBC relaying if desired
Yes, this is also what I want most as developer.
It would be fantastic when the juno repo includes these functions.

**Comment by Reecepbcups** [comment]
This is being worked on out of this repo now. Currently it is found via https://github.com/Reecepbcups/local-interchain - in the future, it will be moved to upstream via Strangelove's repo here: https://github.com/strangelove-ventures/interchaintest

This new local-interchain is much better than a localjuno ever could have been on its own - this also includes IBC support, and the ability to program in any language on top of it to interact
