### ISSUE TITLE
Codeowners inactive 

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#674]
Recently we set up a codeowners file. 

None of the code owners does code reviews excepting @Reecepbcups.

We should probably get rid of that thing. Having a code owner's file that is full of absentees helps no one.

Code reviews have ceased happening, except by me and @Reecepbcups.

**Comment by dimiandre** [comment]
We are not absent

**Comment by faddat** [comment]
Why are there no reviews sir?

It has been weeks.  

The code reviews do not happen.

**Comment by faddat** [comment]
Now it's clear that @dimiandre isn't inactive.

**Comment by Reecepbcups** [comment]
Do not see a reason this should be left open. If we have issues with reviews I will talk with Jack and see if I can get someone from SL to help & get added to code owners
