### ISSUE TITLE
remove x/params

### ISSUE THREAD

**Issue by dimiandre** [CosmosContracts/juno#694]
Many modules we have still depend on x/params

We should remove all references to it and implement their own params store for each module. 

an example on how to do is here https://github.com/cosmos/cosmos-sdk/pull/12363

**Comment by Reecepbcups** [comment]
Thanks! Yea I was hoping to have this done in my cleanup branch this week. got pushed back for the v15 upgrade though

that + the migration is the last major milestone left other than adding more ictest & shipping

**Comment by Reecepbcups** [comment]
Completed in other merged PRs for each module
