### ISSUE TITLE
Account recover fails

### ISSUE THREAD

**Issue by Mehul0011** [CosmosContracts/juno#742]
#### Specifications
Ubuntu latest

Juno version: v15.0.0
OS & Version: Linux

#### Expected behavior
Account must get recovered after proper bip39 mnemonic and passphrase

#### Actual behavior

Fails recovering with this error.
Error: Wrong entropy + checksum size - expected 231, got 242

#### Steps to reproduce the behavior
junod keys add [name] --recover
Give the bip39, which fails

Error: Wrong entropy + checksum size - expected 231, got 242

**Comment by Reecepbcups** [comment]
@Mehul0011 are you sure the mnemonic you input has all words? 

ex: if it is 24 words, that you did not only input 23 words or 25 accidentally

**Comment by Mehul0011** [comment]
I solved the above but I am facing this issue which I am not able to debug.

![image](https://github.com/CosmosContracts/juno/assets/75808688/da3d5856-d95f-42cd-af7a-9c6d6c93e84e)


I have tried setting up my pass init, after creating the gpg key. In such a case it fails telling no public key found/secret found

**Comment by Reecepbcups** [comment]
@Mehul0011 Try --keyring-backend=os at the end (remove the new line & password thing for now)

then input your password manually to setup your keyring
