### ISSUE TITLE
`junod config output json` not working

### ISSUE THREAD

**Issue by taitruong** [CosmosContracts/juno#763]
#### Specifications

Juno version: v16.0.0-alpha.1
OS & Version: Ubuntu
Commit hash: 

#### Expected behavior

output is set

#### Actual behavior

output is unchanged in config

**Comment by Reecepbcups** [comment]
I just tested locally no issue. Ensure you are not using an ENV variable like JUNOD_HOME which changes where the config is stored (default is at $HOME/.juno)
```
(0) reece@reece-x1 [~/Desktop/Programming/Blockchain/juno]
((HEAD detached at v16.0.0-alpha.1)) -> $ junod config
{
        "chain-id": "local-1",
        "keyring-backend": "test",
        "output": "text",
        ...
}

(0) reece@reece-x1 [~/Desktop/Programming/Blockchain/juno]
((HEAD detached at v16.0.0-alpha.1)) -> $ junod config output json

(0) reece@reece-x1 [~/Desktop/Programming/Blockchain/juno]
((HEAD detached at v16.0.0-alpha.1)) -> $ junod config
{
        "chain-id": "local-1",
        "keyring-backend": "test",
        "output": "json",
        ....
```

**Comment by taitruong** [comment]
Thx, tested it and it works. Dunno know what the problem was. Sorry for the inconvenience.
