### ISSUE TITLE
Upgrade wasmvm

### ISSUE THREAD

**Issue by the-frey** [CosmosContracts/juno#83]
Patch version is out, we need to bump version and upgrade https://github.com/CosmWasm/wasmvm

**Comment by faddat** [comment]
Can't solely bump.  I'm working on this but have a number of other things rolling, too.  Hope to complete it over the weekend of Nov 20-21..

**Comment by faddat** [comment]
think we're good here.

**Comment by faddat** [comment]
Testing should be improved.
