### ISSUE TITLE
Set upload fees for contracts higher

### ISSUE THREAD

**Issue by JakeHartnell** [CosmosContracts/juno#85]
It should cost more to upload a contract. I believe there is already a parameter for this? Let's update it on the Uni testnet.

If there is not a parameter, we should add this feature. Transactions should be cheap, but uploading a contract should be expensive.

**Comment by blockcreators** [comment]
Governance can change it later but what do you think the initial cost per byte should be?
And how much would the average contract be? (byte cost * average contract bytes)

To make a simple token via junomint, how much do we expect it to cost?

**Comment by the-frey** [comment]
...which I guess in practical terms needs I need to write the checklist lol

**Comment by JakeHartnell** [comment]
> ...which I guess in practical terms means I need to write the checklist lol

Appreciate all your help on this. :pray:

**Comment by JakeHartnell** [comment]
> ...which I guess in practical terms means I need to write the checklist lol

Let's try to keep the list here in GitHub issues. Let's try to use this Milestone: https://github.com/CosmosContracts/juno/milestone/1

**Comment by the-frey** [comment]
okay so there's also the upload size to consider too.

In wasm;

```go
// DefaultMaxWasmCodeSize limit max bytes read to prevent gzip bombs
DefaultMaxWasmCodeSize = 600 * 1024 * 2
```
and

    junod query params subspace wasm maxWasmCodeSize --chain-id uni

confirms we are using default

```
key: maxWasmCodeSize
subspace: wasm
value: '"1228800"'
```

**Comment by JakeHartnell** [comment]
> While the various costs are specified https://github.com/CosmWasm/wasmd/blob/57517b0c333e23aedd2bbccf80579cf75081241b/x/wasm/keeper/gas_register.go#L13
> 
> With reasoning https://github.com/CosmWasm/cosmwasm/blob/v1.0.0-beta/docs/GAS.md

Good find! Looks like this is maybe what we want:
```
	// DefaultCompileCost is how much SDK gas is charged *per byte* for compiling WASM code.
	// Benchmarks and numbers were discussed in: https://github.com/CosmWasm/wasmd/pull/634#issuecomment-938056803
	DefaultCompileCost uint64 = 3
```

**Comment by the-frey** [comment]
Yup, although it's hard coded AFAICT which would mean forking. AFAIUI changes there are consensus-breaking, hence why they aren't params. That said, it's lateish in the day and my caffiene level is drooping so may have that wrong.

**Comment by faddat** [comment]
hate that caffeine drooping feeling

**Comment by the-frey** [comment]
I have a path to doing this, but given that Confio (as per the reasoning & discussion links above) have thought about this a fair bit, I am... still not sold on overriding these values. 

Moreover, if we were to override these values we'd have to do a few more rounds of testing. Which isn't necessarily a bad thing, but November is flying by...

**Comment by JakeHartnell** [comment]
> I have a path to doing this, but given that Confio (as per the reasoning & discussion links above) have thought about this a fair bit, I am... still not sold on overriding these values.
> 
> Moreover, if we were to override these values we'd have to do a few more rounds of testing. Which isn't necessarily a bad thing, but November is flying by...

Confio thought about these values in the context on Confio and tgrade, we need to think about them in the context of Juno.

> Yup, although it's hard coded AFAICT which would mean forking. AFAIUI changes there are consensus-breaking, hence why they aren't params.

Well we already have a fork. Would be great to make some of these params and contribute that upstream. Having `DefaultCompileCost` as a param would be the best option for us going forward.

**Comment by JakeHartnell** [comment]
@the-frey, I know you had a name service contract right?

**Comment by the-frey** [comment]
Yep, I've got a nameservice NFT contract, why?

**Comment by JakeHartnell** [comment]
Lol, wrong GitHub thread. :facepalm:

**Comment by the-frey** [comment]
FWIW I'm not against changing this and then testing, it's a bunch more stuff to test. It's potentially doable in base Juno, no fork required - but I _am_ against making them params. At the minute I'm dubious about exposing something that's an obvious attack vector to governance. Could be convinced in future however.

**Comment by the-frey** [comment]
Okay have spiked something on https://github.com/CosmosContracts/juno/tree/override_cw_default_compile_costs - don't think it's quite there yet. Need to test a couple of things before PR
