### ISSUE TITLE
x/clock - permissionless

### ISSUE THREAD

**Issue by Reecepbcups** [CosmosContracts/juno#861]
- like feepay, allow a dev to put some funds in to pay for execution fees
- Free execution up to 100k gas, then a reduced ujuno fee compare to globalfee (ex: 0.075ujuno is current. for this maybe charge 0.00075ujuno*gas each block. something reasonable)
- if a contract execute fails enough (ex: no sudo message) "jail" the contract. small fee to unjail

**Comment by joelsmith-2019** [comment]
Discussed with @Reecepbcups, we will not be implementing fees for clock contracts. So, that being said, contracts will not need to be funded nor will they be allowed to exceed 100k gas consumed.
