### ISSUE TITLE
panic: While parsing config: toml: expected newline but got U+0022 '"'

### ISSUE THREAD

**Issue by taitruong** [CosmosContracts/juno#866]
I'm using v17.1.1 and did this:

```sh
export OUTPUT="json"
OUTPUT='{"":""}'
junod config node https://uni-rpc.reece.sh:443
```

Now `junod config` throws this error:

```sh
panic: While parsing config: toml: expected newline but got U+0022 '"'

goroutine 1 [running]:
github.com/CosmosContracts/juno/v17/cmd/junod/cmd.SetCustomEnvVariablesFromClientToml({{0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0}, {0x342bf80, 0xc000f49ee0}, ...})
        github.com/CosmosContracts/juno/v17/cmd/junod/cmd/root.go:163 +0x20e
github.com/CosmosContracts/juno/v17/cmd/junod/cmd.NewRootCmd()
        github.com/CosmosContracts/juno/v17/cmd/junod/cmd/root.go:69 +0x7f8
main.main()
        github.com/CosmosContracts/juno/v17/cmd/junod/main.go:16 +0x1c
```

And now in `client.toml` this has changed: `output = "{"":""}"`

**Comment by taitruong** [comment]
If I fix `client.toml`, and checking config by `junod config`, it still shows:

```json
{
        "chain-id": "uni-6",
        "keyring-backend": "os",
        "output": "{\"\":\"\"}",
        "node": "https://uni-rpc.reece.sh:443",
        "broadcast-mode": "sync",
        "gas": "auto",
        "gas-prices": "",
        "gas-adjustment": "",
        "fees": "",
        "fee-granter": "",
        "fee-payer": "",
        "note": ""
}
```

Seems like junod is pointing to some other dir?!

**Comment by Reecepbcups** [comment]
Thanks for the report, this is reproducible on my end.

This is an SDK level issue as it does not use the envPrefix for setting the output.

It *should* require `JUNOD_OUTPUT=json` but does not. Also I do not think it is even supposed to set in this context? Either way these client configurations are upstream. Please make a report to: https://github.com/cosmos/cosmos-sdk

(This affects Gaia as well, not just Juno)

**Comment by taitruong** [comment]
Created SDK issue: https://github.com/cosmos/cosmos-sdk/issues/18332
