### ISSUE TITLE
[Every Juno User's Problem] Code assessment

### ISSUE THREAD

**Issue by faddat** [CosmosContracts/juno#973]
This assessement was driven by this communication by a Strangelove labs engineer:

![image](https://github.com/CosmosContracts/juno/assets/7142025/78bec0be-bd52-40b0-8c58-4d1ca1a4f370)

It seems to indicate that there is some kind of known issue in Juno (I'm aware of a few) but doesn't expand on it.  If anyone is aware of this specific issue, it's probably a great idea to say here, clearly, as there aren't any clear indications as to what the future problem is, driven by some kind of small number.  

I am, of course, aware that in addition to fixing a virtual machine, some transfers of funds occurred in v19.1.0.

But I don't know if that is the actual problem, and whatever the "future problem" is it does not only affect developers... it affects every Juno holder. 

## Dependencies

Juno uses interchaintest for testing, and the ibc-v7 / sdk 47 version of interchain test isn't being maintained.  This prevents upgrades of cosmos-sdk on the v0.47.x line, though it might be possible to keep support for interchaintest and move to SDK 50, though there have been widespread reports of issues with Comet v0.38.x

## Fee Share

Recent developments on [redacted] have shown that Juno is likely better off without fee share.  It's my opinion that it should be removed. 

....will write more later, though it may be a few days.

**Comment by Reecepbcups** [comment]
>  ibc-v7 / sdk 47 version of interchain test isn't being maintained
This is false, you just don't know how to dump a nested go.mod version

The information can be found here where i got the screenshot
https://daodao.zone/dao/juno1gyjl26rnqqyk6cuh6nqtvx8t885jgqagusvpqpvtgaygcjg2wjdqz0rzle/proposals/A7

The "future problem" was an accounting offset, where 530k was transfered instead of a full 5.3m. It has since been corrected, the meme served its purpose

**Comment by faddat** [comment]
<img width="793" alt="Screenshot 2024-03-02 at 1 01 04 AM" src="https://github.com/CosmosContracts/juno/assets/7142025/47254c7d-148e-4201-8d9a-7cce0106d8b8">

The current v47 cosmos-sdk is v0.47.10
The current v47 wasmd is v0.45.x
The current v37 cometbft is v0.37.4
the current ibc is v7.3.2
the current ics is v4, not v3


and the interchaintest dependency is why Juno can't use sdk v0.47.10

**Comment by Reecepbcups** [comment]
Working on it here: https://github.com/CosmosContracts/juno/pull/977

Please make payable to noble1reece3m8g4m3d0qrpj93rnnseudnpzhr380amd

cometbft v0.37.4
cosmos-sdk v0.47.10
IBC v7 v7.3.2
math v1.3.0
ictest v7.0.0 public release, that commit is not a release branch yet. So using what is public

https://x.com/Reecepbcups_/status/1763754087122706880?s=20

**Comment by faddat** [comment]
Reece, I regret to inform you that the solution you've posited to the bounty, fails to accomplish the goals of the bounty.

Your solution was to use a replace statement to lower the version of cometbft in github.com/cosmoscontracts/juno/v20interchaintest/go.mod to v0.37.2 and does not eliminate the use of obsolete code in juno. 

What you've proven is that `interchaintest` requires that developers dance around it with replace statements and the like -- in fact you've proven my point entirely.

Thank you for your submission.

**Comment by faddat** [comment]
Closing this issue, since @Reecepbcups says that his meme was effective and there's no longer a situation of "its fine since its such a small amount"
