### ISSUE TITLE
Better tagging of containers in registry

### ISSUE THREAD

**Issue by the-frey** [CosmosContracts/juno#98]
At the moment there is only `latest` AFAICT

https://github.com/CosmosContracts/juno/pkgs/container/juno

Would be nice if this was created in such a way that tags were applied that match releases, for dev purposes

**Comment by JakeHartnell** [comment]
#107 is potentially related?

**Comment by the-frey** [comment]
![C-658VsXoAo3ovC](https://user-images.githubusercontent.com/2385077/144013927-aedac0ee-9566-4e2d-9992-6ba6fad36a24.jpg)

**Comment by the-frey** [comment]
What remains to be seen is how the github CI improvements react to tags. It _should_ tag and release when you tag, but I don't know if that means it expects the tag to be tagged and pushed from the dev machine _when it lands on GitHub_

**Comment by the-frey** [comment]
Huh, looks like it still isn't quite detecting the tags right. FFS.

Will add this back to my to-do list.

**Comment by the-frey** [comment]
Aha. Tagging only works for _pushing tags_ and releases/tags via UI is a separate event. PLUS

> Note: The release event is not triggered for draft releases.

Which is why current draft isn't picked up.

**Comment by the-frey** [comment]
Release tagging can now be seen working on `main`. Might disable PR tagging at some point however.
