### ISSUE TITLE
Guidance Request on Ethermint Integration with Cosmos SDK

### ISSUE THREAD

**Issue by aansheng** [CosmosContracts/juno#986]
Hello,

I am exploring the possibility of integrating Ethermint with the Cosmos SDK for a project I am working on. While researching, I came across your project, which seems to have successfully implemented this integration. Given the complexity and the lack of maintained documentation on Ethermint, I am reaching out to seek your assistance.

Would it be possible for you to share any documentation, guidelines, or even the specific pull requests (PRs) or commits that detail how you integrated Ethermint with the Cosmos SDK? Insights into the challenges faced and solutions implemented during your integration process would be incredibly valuable.

Understanding your approach and learning from your experience would be immensely helpful for my project, especially to ensure seamless Ethereum compatibility within a Cosmos SDK-based blockchain.

Thank you for considering my request. I look forward to any information you can provide.

Best regards,

**Comment by terry1ee** [comment]
> This project does not use Ethermint. : )

Thank you for the clarification. I see now that Juno leverages CosmWasm for smart contracts. It's interesting to observe different implementations in the Cosmos ecosystem, and I appreciate your quick response to clear up my confusion.
